# Generated by Django 4.2.1 on 2023-05-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_tag',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='q_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question', to_field='q_tag'),
        ),
    ]
